### ISSUE TITLE
hello have you got an updated version of     Kitronik-Pico-Discovery-Kit  /Experiment_7.py

### ISSUE THREAD

**Issue by camelPico** [KitronikLtd/Kitronik-Pico-Discovery-Kit#1]
i cant get the buttons to work nor the buzzer, on Kitronik-Pico-Discovery-Kit Experiment_7 ,
ive tryed everything i can think of and woundering if its your code, 
thank you

**Comment by KitronikLtd** [comment]
Hi there! Sorry for taking so long to get back to you - we can assure you the code works as expected!
If you still have any further issues, please contact our helpdesk using this online form:
https://kitronik.co.uk/pages/contact-us

Kind Regards, 
Jake
